### ISSUE TITLE
Differences between 1.0 and 1.0.1

### ISSUE THREAD

**Issue by clh5** [oracle/solaris-openssl-fips#3]
Can you confirm the the differences between the two versions are limited to the following 2 files: 
README.md and oracle-openssl-fips.license ? Thanks.

**Comment by vladak** [comment]
Anyone can unpack the tarballs and do the recursive comparison themselves. Why do you need to know ?

**Comment by clh5** [comment]
Just want to know if we should upgrade to the newer version. If it's only changes in license and readme, we do not need to rebuild and retest. Open source projects usually provide release notes to let users know what's in a new release, so I don't think my question is out of line,.

**Comment by vladak** [comment]
This is not a usual open source project per se. This particular repository serves to build OpenSSL for Oracle customers. If you have any questions, please reach out to Oracle support.
